print("There are many {ADJECTIVE} ways to choose a/an {NOUN} to read.")
print("An adjective: ")
ADJ = input()
print("A noun: ")
NO = input()
print("First you could ask for recommendations from your friends and {PLURAL NOUN}.")
print("A plural noun: ")
PLUNO = input()
print("Just dont ask Aunt {PERSON IN ROOM FEMALE}- she only reads {ADJECTIVE} books with {ARTICLE OF CLOTHING}- ripping goddesss on the cover.")
print("A person in room female: ")
PEROFE= input()
print("Another adjective: ")
ADJ2= input()
print("An article of clothing: ")
ARTCLO= input()
print("There are many ",ADJ," ways to choose a/an ",NO," to read. First you could ask for recommendations from your friends and ",PLUNO,". Just dont ask Aunt ",PEROFE,"- she only reads ",ADJ2," books with ",ARTCLO,"- ripping goddesss on the cover. ")
